spring:
#  security:
#    jwt:
#      secret: "Y3JlYXRlX2FfcmFuZG9tX2NvZGVyX2p3dA=="
  datasource:
    url: ${JAVA_COURSE_DB_URL}
    username: ${JAVA_COURSE_DB_USERNAME}
    password: ${JAVA_COURSE_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    default-schema: gym_app